inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops:           enable
  DisplayStyleGuide: true
  DisabledByDefault: false
  TargetRubyVersion: 3.1
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*
    - spec/**/*

Naming/InclusiveLanguage:
  Enabled: false

Layout/LineLength:
  Max: 180

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Metrics/BlockLength:
  Max: 45
  IgnoredMethods: ['describe', 'xdescribe', 'context', 'let']

Metrics/ClassLength:
  Max: 200


#
# Bundler
#
Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

#
# Rspec
#
RSpec/LetSetup:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/StubbedMock:
  Enabled: true

#
# Styling
#
Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CaseLikeIf:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true
  Exclude:
    - app/services/transactions_filter_service.rb

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: true
  Severity: info


Style/SymbolArray:
  Enabled: true
  MinSize: 4


#
# Layouts
#

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_first_element

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
  Severity: info

Layout/ExtraSpacing:
  Enabled:           false
  AllowForAlignment: true
  Severity:          info

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Layout/MultilineAssignmentLayout:
  EnforcedStyle: new_line

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled:  true
  Severity: info

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact


#
# Linting
#

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

#
# Security
#
Security/YAMLLoad:
  Enabled: false

#
# Naming
#

#
# Rails
#
Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_iso_numeric

Rails/FindEach:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - acceptance
    - development
    - test
